<?php

namespace MMH\SiteBundle\Repository;

/**
 * imageProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
