<?php

namespace MMH\SiteBundle\Repository;

/**
 * imageArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
