<?php

namespace MMH\SiteBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

  // Fetch Projects + image + paiments

  public function getProjectWithPayment()
  {

    // $query = $this->_em->createQuery('SELECT p, pay, img FROM MMHSiteBundle:Project p JOIN p.payment pay JOIN p.imageproject img WHERE p.visibility=true ORDER BY p.startDate DESC');
    // $results = $query->setMaxResults(6)->getResult();
    // return $results;

      return $this->createQueryBuilder('p')
      ->where ("p.visibility = :visibility")
      ->setParameter("visibility", true)
      ->leftJoin('p.payment', 'pay')
      ->addSelect('pay')
      ->innerJoin('p.imageproject', 'img')
      ->addSelect('img')
      ->orderBy('p.startDate', 'DESC')
      ->getQuery()
      ->getResult();
  }

  // Fetch showcased Projects

  public function getProjectForSlider() {

    $qb =  $this->createQueryBuilder('p');
    $qb
      ->where ("p.slider = :bool")
      ->setParameter("bool", 1)
      ;
      return $qb
    ->leftJoin('p.payment', 'pay')
    ->addSelect('pay')
    ->innerJoin('p.imageproject', 'img')
    ->addSelect('img')
    ->getQuery()
    ->getResult();
  }

  // Fetch project matching slug

  public function getProjectWithImage($slug)
  {
    $qb =  $this->createQueryBuilder('p');
    $qb
      ->where ("p.slug = :slug")
      ->setParameter("slug",$slug)
      ;
      return $qb
    ->leftJoin('p.payment', 'pay')
    ->addSelect('pay')    
    ->innerJoin('p.imageproject', 'img')
    ->addSelect('img')
    ->leftJoin('p.values', 'val')
    ->addSelect('val')
    ->leftJoin('p.comments', 'com')
    ->orderBy('com.date', 'desc')
    ->addSelect('com')

    ->getQuery()
    ->getResult();
  }

}
