<?php

namespace MMH\SiteBundle\Repository;

/**
 * ValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueRepository extends \Doctrine\ORM\EntityRepository
{
}
